modLoader = "javafml"
loaderVersion = "[1,)"
license = "GPL v3"

[[mods]]
modId = "cobblebonus"
version = "${version}"
displayName = "CobbleBonus"
authors = "Pikapowner"
description = '''
Permanent shiny and capture modifiers for Cobblemon players.
'''

[[dependencies.cobblebonus]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "SERVER"

[[dependencies.cobblebonus]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.219,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.cobblebonus]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.7.3,)"
ordering = "AFTER"
side = "SERVER"
