modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/example/cobblebonus/issues"
license = "GPL v3"

[[mods]]
modId = "cobblebonus"
version = "${version}"
displayName = "CobbleBonus"
authors = "CobbleBonus Team"
description = '''
Permanent per-player multipliers for Cobblemon shiny chance and catch rate.
'''
#logoFile = ""

[[dependencies.cobblebonus]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblebonus]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.219,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblebonus]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.7.3,)"
ordering = "AFTER"
side = "BOTH"
